{\rtf1\ansi\ansicpg1252\cocoartf2761
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red27\green27\blue27;\red247\green247\blue247;\red181\green0\blue19;
\red73\green17\blue135;\red50\green91\blue97;\red151\green0\blue126;}
{\*\expandedcolortbl;;\cssrgb\c14118\c14118\c14118;\cssrgb\c97647\c97647\c97647;\cssrgb\c76863\c10196\c8627;
\cssrgb\c36078\c14902\c60000;\cssrgb\c24706\c43137\c45490;\cssrgb\c66667\c5098\c56863;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 image: openjdk:11-jdk\
\
variables:\
  ANDROID_COMPILE_SDK: \cf4 \strokec4 "30"\cf2 \strokec2 \
  ANDROID_BUILD_TOOLS: \cf4 \strokec4 "30.0.3"\cf2 \strokec2 \
  ANDROID_SDK_TOOLS: \cf4 \strokec4 "7583922"\cf2 \strokec2 \
\
before_script:\
  - apt-get --quiet update --\cf5 \strokec5 yes\cf2 \strokec2 \
  - apt-get --quiet install --\cf5 \strokec5 yes\cf2 \strokec2  wget tar unzip lib32stdc++6 lib32z1\
\
  - \cf5 \strokec5 export\cf2 \strokec2  ANDROID_HOME=\cf4 \strokec4 "\cf6 \strokec6 $\{PWD\}\cf4 \strokec4 /android-home"\cf2 \strokec2 \
  - install -d \cf6 \strokec6 $ANDROID_HOME\cf2 \strokec2 \
\
  - wget --output-document=\cf6 \strokec6 $ANDROID_HOME\cf2 \strokec2 /cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-\cf6 \strokec6 $\{ANDROID_SDK_TOOLS\}\cf2 \strokec2 _latest.zip\
\
  - \cf5 \strokec5 pushd\cf2 \strokec2  \cf6 \strokec6 $ANDROID_HOME\cf2 \strokec2 \
  - unzip -d cmdline-tools cmdline-tools.zip\
  - \cf5 \strokec5 pushd\cf2 \strokec2  cmdline-tools\
\
  - \cf5 \strokec5 mv\cf2 \strokec2  cmdline-tools tools || \cf7 \strokec7 true\cf2 \strokec2 \
  - \cf5 \strokec5 popd\cf2 \strokec2 \
  - \cf5 \strokec5 popd\cf2 \strokec2 \
  - \cf5 \strokec5 export\cf2 \strokec2  PATH=\cf6 \strokec6 $PATH\cf2 \strokec2 :\cf6 \strokec6 $\{ANDROID_HOME\}\cf2 \strokec2 /cmdline-tools/tools/bin/\
\
  - sdkmanager --version\
\
  - \cf5 \strokec5 yes\cf2 \strokec2  | sdkmanager --licenses || \cf7 \strokec7 true\cf2 \strokec2 \
  - sdkmanager \cf4 \strokec4 "platforms;android-\cf6 \strokec6 $\{ANDROID_COMPILE_SDK\}\cf4 \strokec4 "\cf2 \strokec2 \
  - sdkmanager \cf4 \strokec4 "platform-tools"\cf2 \strokec2 \
  - sdkmanager \cf4 \strokec4 "build-tools;\cf6 \strokec6 $\{ANDROID_BUILD_TOOLS\}\cf4 \strokec4 "\cf2 \strokec2 \
\
  - apt-get -qq update\
  - apt-get install -qqy --no-install-recommends build-essential ruby-full\
  - gem install bundler\
  - bundle install\
\
  - \cf5 \strokec5 chmod\cf2 \strokec2  +x ./gradlew\
\
stages:\
  - \cf5 \strokec5 test\cf2 \strokec2 \
  - build\
  - deploy\
\
testDebug:\
  stage: \cf5 \strokec5 test\cf2 \strokec2 \
  script:\
    - ./gradlew \cf5 \strokec5 test\cf2 \strokec2 \
\
assembleDebug:\
  interruptible: \cf7 \strokec7 true\cf2 \strokec2 \
  stage: build\
  script:\
    - ./gradlew assembleDebug\
  artifacts:\
    paths:\
      - app/build/outputs/\
\
deploy-internal-app-bundle:\
  stage: deploy\
  script:\
    - bundle \cf5 \strokec5 exec\cf2 \strokec2  fastlane internal}