# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Internal Build to Play Store"
  lane :internal do
   previous_build_number = google_play_track_version_codes(track: "production")[0]
   current_build_number = previous_build_number + 1
   gradle(
      task: "bundle",
      build_type: 'release',
      properties: {
        "android.injected.signing.store.file" => ENV['PWD'] + "/Users/jaindeepak/Documents/development/app-certificates/movie-list-app",
        "android.injected.signing.store.password" => "123456",
        "android.injected.signing.key.alias" => "Movie",
        "android.injected.signing.key.password" => "123456",
        "android.injected.version.code" => current_build_number
      })
    upload_to_play_store(
      track: 'internal',
      release_status: 'completed',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_apk: true,
      skip_upload_screenshots: true)
  end
end